"use client";
import { useState, useTransition } from "react";
import { Check, Pencil, TriangleAlert } from "lucide-react";
import { useTranslations } from "next-intl";
import { usePathname, useRouter } from "@/i18n/navigation";
import { formatCents } from "@/lib/calc";
import { renameProduct, setMenuItemActive } from "@/lib/actions/menuItems";
import type { IngredientOption, MenuItemForEdit } from "@/lib/data/getMenuItemsForEdit";
import type { MenuControlItem } from "@/lib/data/getMenuControlCenter";
import type { IngredientUnitConversion } from "@/lib/calc/recipeUnits";
import type { ProductPhoto } from "@/lib/data/getProductPhoto";
import { getItemPricingStatus } from "@/lib/viewmodels/menuCatalogViewModel";
import type { MenuDetailTab } from "@/lib/viewmodels/menuDetail";
import { stableSortSizes } from "@/lib/menu/sizeLabel";
import { usePricingStatusChip } from "./usePricingStatusChip";
import ProductPhotoEditor from "./ProductPhotoEditor";
import PriceEditor from "./PriceEditor";
import RecipeMatrix from "./RecipeMatrix";

type Period="today"|"days7"|"days30";
export default function ProductDetailScreen({item,editItem,ingredients,ingredientConversions,siblingSizes,productEditItems,photo,businessId,focusedSizeId,initialTab}:{item:MenuControlItem;editItem:MenuItemForEdit;ingredients:IngredientOption[];menuGroupOptions:string[];ingredientConversions:Record<string,IngredientUnitConversion[]>;siblingSizes:MenuControlItem[];productEditItems:MenuItemForEdit[];photo:ProductPhoto;businessId:string|null;focusedSizeId?:string;justCreated?:boolean;initialTab:MenuDetailTab;initialEditing?:boolean;copiedFrom?:string}){
 const t=useTranslations("Menu");const te=useTranslations("ManageMenu");const router=useRouter();const pathname=usePathname();const statusChip=usePricingStatusChip();const [tab,setTab]=useState(initialTab);const [period,setPeriod]=useState<Period>("days30");const [priceItem,setPriceItem]=useState<MenuControlItem|null>(null);const [renaming,setRenaming]=useState(false);const [name,setName]=useState(item.baseName);const [pending,start]=useTransition();const [error,setError]=useState<string|null>(null);const all=stableSortSizes([item,...siblingSizes]);
 function navigate(next:MenuDetailTab,size?:string){setTab(next);router.replace(`${pathname}?tab=${next}${size?`&size=${encodeURIComponent(size)}`:""}`,{scroll:false});}
 function saveName(){start(async()=>{const r=await renameProduct({menuItemId:item.id,name});if(r.ok){setRenaming(false);router.refresh();}else setError(r.error);});}
 return <>
  <section className="grid gap-4 rounded-card-lg bg-card p-[18px] md:grid-cols-[260px_1fr]">
   <ProductPhotoEditor menuItemId={item.id} businessId={businessId} photo={photo} labels={{photo:t("addPhoto"),change:t("changePhoto"),remove:t("removePhoto"),error:t("photoError")}}/>
   <div className="flex flex-col justify-center">{renaming?<div className="flex flex-wrap gap-2"><input className="h-12 min-w-0 flex-1 rounded-lg border border-line px-3 text-xl font-bold" value={name} onChange={e=>setName(e.target.value)}/><button type="button" onClick={saveName} disabled={pending} className="min-h-12 rounded-full bg-ink px-4 font-bold text-paper">{te("saveChanges")}</button><button type="button" onClick={()=>setRenaming(false)} className="min-h-12 px-3 font-bold">{te("cancel")}</button></div>:<div className="flex items-center gap-2"><h1 className="font-headline text-4xl font-bold">{item.baseName}</h1><button type="button" onClick={()=>setRenaming(true)} aria-label={t("editProductName")} className="min-h-12 min-w-12"><Pencil className="mx-auto" size={19}/></button></div>}<p className="mt-1 text-ink-muted">{t("productWorkspace",{count:all.length})}</p>{error&&<p className="text-sm text-warn">{error}</p>}</div>
  </section>
  <div className="flex gap-2 overflow-x-auto" role="tablist">{(["overview","recipe","pricing"] as const).map(k=><button key={k} type="button" role="tab" aria-selected={tab===k} onClick={()=>navigate(k)} className={`min-h-12 rounded-full px-5 font-bold ${tab===k?"bg-ink text-paper":"bg-card"}`}>{t(k==="overview"?"tabOverview":k==="recipe"?"tabRecipe":"tabPricing")}</button>)}</div>
  {tab==="overview"&&<><div className="flex rounded-full bg-card p-1" aria-label={t("salesPeriod")}>{(["today","days7","days30"] as const).map(p=><button key={p} type="button" aria-pressed={period===p} onClick={()=>setPeriod(p)} className={`min-h-12 flex-1 rounded-full px-2 text-sm font-bold ${period===p?"bg-ink text-paper":"text-ink-muted"}`}>{t(p==="today"?"today":p==="days7"?"last7Days":"last30Days")}</button>)}</div><div className="grid gap-3 lg:grid-cols-3">{all.map(size=><SizeCard key={size.id} size={size} units={size.unitsSoldByPeriod?.[period]??0} t={t} chip={statusChip(size)} onPrice={()=>setPriceItem(size)} onRecipe={()=>navigate("recipe",size.id)} onArchive={()=>start(async()=>{const r=await setMenuItemActive(size.id,false);if(r.ok)router.refresh();else setError(r.error)})}/>)}</div>{priceItem&&<PriceEditor item={priceItem} onCancel={()=>setPriceItem(null)} labels={{title:t("editPrice"),size:t("selectedSize"),current:t("currentPrice"),suggested:t("suggested"),price:t("sellingPrice"),save:te("saveChanges"),cancel:te("cancel")}}/>}</>}
  {tab==="recipe"&&<RecipeMatrix items={productEditItems} ingredients={ingredients} ingredientConversions={ingredientConversions} focusedSizeId={focusedSizeId} labels={{ingredient:t("ingredient"),focused:t("focusedSize"),noRecipe:t("noRecipe"),missingCost:t("recipeMissingCostReason"),add:t("add"),remove:te("remove"),addIngredient:te("addIngredient"),addTo:t("addToSize"),search:te("ingredientSearchLabel"),create:te("newIngredient"),name:te("ingredientLabel"),quantity:te("quantityLabel"),cancel:te("cancel"),save:te("saveChanges"),saved:t("recipeSaved"),partialSave:t("recipePartialSave"),g:t("weight"),ml:t("volume"),each:t("count"),fl_oz:te("recipeUnitFlOz"),shot:te("recipeUnitShot"),pump:te("recipeUnitPump")}}/>}
  {tab==="pricing"&&<section className="rounded-card-lg bg-card p-[18px]"><h2 className="text-xl font-bold">{t("pricingAllSizes")}</h2><div className="mt-3 grid gap-2">{all.map(s=>{const pricing=getItemPricingStatus(s);return <button key={s.id} type="button" onClick={()=>setPriceItem(s)} className="flex min-h-16 items-center justify-between rounded-xl border border-line p-3 text-start"><span><strong>{s.sizeLabel??s.name}</strong><span className="block text-sm text-ink-muted">{(pricing.kind==="low"||pricing.kind==="high")?t("suggestedPrice",{amount:formatCents(pricing.suggestedPriceCents)}):statusChip(s).label}</span></span><strong>{formatCents(s.priceCents)}</strong></button>})}</div></section>}
 </>;
}
function SizeCard({size,units,t,chip,onPrice,onRecipe,onArchive}:{size:MenuControlItem;units:number;t:ReturnType<typeof useTranslations<"Menu">>;chip:{label:string;good:boolean};onPrice:()=>void;onRecipe:()=>void;onArchive:()=>void}){const ready=size.costStatus==="READY"&&size.ingredientsCostCents!==null;return <article className="rounded-card-lg bg-card p-4"><div className="flex items-center justify-between"><h2 className="text-xl font-bold">{size.sizeLabel??size.name}</h2><span className={`flex items-center gap-1 text-sm font-bold ${chip.good?"text-good":"text-warn"}`}>{chip.good?<Check size={15}/>:<TriangleAlert size={15}/>} {chip.label}</span></div><dl className="mt-2 grid grid-cols-2 gap-x-3 gap-y-1 text-sm"><dt className="text-ink-muted">{t("sellingPrice")}</dt><dd className="text-end font-bold">{formatCents(size.priceCents)}</dd><dt className="text-ink-muted">{t("costToMake")}</dt><dd className="text-end font-bold">{ready?formatCents(size.ingredientsCostCents!):t("needsReview")}</dd><dt className="text-ink-muted">{t("keptAfterIngredients")}</dt><dd className="text-end font-bold text-good">{ready?formatCents(size.priceCents-size.ingredientsCostCents!):"—"}</dd><dt className="text-ink-muted">{t("unitsSold")}</dt><dd className="text-end font-bold">{units}</dd><dt className="text-ink-muted">{t("recipeStatus")}</dt><dd className={`text-end font-bold ${ready?"text-good":"text-warn"}`}>{ready?t("recipeReady"):t("needsReview")}</dd></dl><div className="mt-3 grid grid-cols-2 gap-2"><button type="button" onClick={onPrice} className="min-h-12 rounded-full border border-line text-sm font-bold">{t("editPrice")}</button><button type="button" onClick={onRecipe} className="min-h-12 rounded-full border border-line text-sm font-bold">{ready?t("editRecipe"):t("needsReview")}</button></div><button type="button" onClick={onArchive} className="mt-1 min-h-12 w-full text-sm font-semibold text-ink-muted">{t("noLongerServing")}</button></article>}
