"use client";
import { useMemo, useState, useTransition } from "react";
import { Plus, Search, Trash2 } from "lucide-react";
import { addRecipeLine, deleteRecipeLine, updateRecipeLine } from "@/lib/actions/menuItems";
import type { IngredientOption, MenuItemForEdit } from "@/lib/data/getMenuItemsForEdit";
import type { BaseUnit, IngredientUnitConversion, RecipeDisplayUnit } from "@/lib/calc/recipeUnits";
import { recipeDisplayUnitsFor } from "@/lib/calc/recipeUnits";
import { useRouter } from "@/i18n/navigation";

type Draft={quantity:string;unit:RecipeDisplayUnit;removed?:boolean};
type StagedAddition={key:string;menuItemId:string;ingredientId?:string;ingredientName:string;baseUnit:BaseUnit;quantity:string;unit:RecipeDisplayUnit};
const draftForLine=(line:MenuItemForEdit["recipe"][number]):Draft=>({quantity:String(line.displayQuantity??line.quantity),unit:(line.displayUnit??line.baseUnit) as RecipeDisplayUnit});
const draftsFromItems=(items:MenuItemForEdit[])=>Object.fromEntries(items.flatMap(i=>i.recipe.map(l=>[`${i.id}:${l.ingredientId}`,draftForLine(l)])));

export default function RecipeMatrix({items,ingredients,ingredientConversions,focusedSizeId,labels}:{items:MenuItemForEdit[];ingredients:IngredientOption[];ingredientConversions:Record<string,IngredientUnitConversion[]>;focusedSizeId?:string;labels:Record<string,string>}){
 const router=useRouter(); const [pending,start]=useTransition(); const [error,setError]=useState<string|null>(null); const [saved,setSaved]=useState(false); const [addTo,setAddTo]=useState<string|null>(null); const [kind,setKind]=useState<BaseUnit>("g"); const [search,setSearch]=useState(""); const [selected,setSelected]=useState<IngredientOption|null>(null); const [creating,setCreating]=useState(false); const [newName,setNewName]=useState(""); const [quantity,setQuantity]=useState(""); const [unit,setUnit]=useState<RecipeDisplayUnit>("g");
 const [drafts,setDrafts]=useState<Record<string,Draft>>(()=>draftsFromItems(items)); const [additions,setAdditions]=useState<StagedAddition[]>([]);
 const rows=useMemo(()=>{const map=new Map<string,string>();items.forEach(i=>i.recipe.forEach(l=>map.set(l.ingredientId,l.ingredientName)));additions.forEach(a=>map.set(a.ingredientId??a.key,a.ingredientName));return [...map].sort((a,b)=>a[1].localeCompare(b[1]));},[items,additions]);
 const filtered=ingredients.filter(i=>i.baseUnit===kind&&i.name.toLowerCase().includes(search.toLowerCase())&&!items.find(x=>x.id===addTo)?.recipe.some(l=>l.ingredientId===i.id)&&!additions.some(a=>a.menuItemId===addTo&&a.ingredientId===i.id));
 const selectedBase=selected?.baseUnit??kind; const selectedUnits=recipeDisplayUnitsFor(selectedBase,selected?ingredientConversions[selected.id]??[]:[]);
 function resetAdd(){setAddTo(null);setSelected(null);setCreating(false);setSearch("");setNewName("");setQuantity("");setUnit("g");}
 function chooseIngredient(ingredient:IngredientOption){setSelected(ingredient);setCreating(false);setUnit(recipeDisplayUnitsFor(ingredient.baseUnit,ingredientConversions[ingredient.id]??[])[0]);}
 function stageAdd(){if(!addTo||(!selected&&!newName.trim())||!(Number(quantity)>0)||!selectedUnits.includes(unit))return;setAdditions(current=>[...current,{key:`new:${Date.now()}:${current.length}`,menuItemId:addTo,ingredientId:selected?.id,ingredientName:selected?.name??newName.trim(),baseUnit:selectedBase,quantity,unit}]);resetAdd();setSaved(false);}
 function cancel(){setDrafts(draftsFromItems(items));setAdditions([]);resetAdd();setError(null);setSaved(false);}
 function save(){setError(null);setSaved(false);start(async()=>{let completed=0;let total=additions.length;for(const item of items)total+=item.recipe.length;for(const item of items)for(const line of item.recipe){const d=drafts[`${item.id}:${line.ingredientId}`];if(!d)continue;const result=d.removed?await deleteRecipeLine(item.id,line.ingredientId):await updateRecipeLine({menuItemId:item.id,ingredientId:line.ingredientId,displayUnit:d.unit,displayQuantity:Number(d.quantity)});if(!result.ok){setError(completed?labels.partialSave:result.error);return;}completed++;}for(const addition of additions){const result=await addRecipeLine({menuItemId:addition.menuItemId,ingredientId:addition.ingredientId,newIngredientName:addition.ingredientId?undefined:addition.ingredientName,newIngredientUnit:addition.ingredientId?undefined:addition.baseUnit,displayUnit:addition.unit,displayQuantity:Number(addition.quantity)});if(!result.ok){setError(completed?labels.partialSave:result.error);return;}completed++;}setSaved(total>0);router.refresh();});}
 return <section className="rounded-card-lg bg-card p-[18px]"><div className="overflow-x-auto"><table className="w-full min-w-[680px] border-separate border-spacing-0"><thead><tr><th className="border-b border-line p-2 text-start">{labels.ingredient}</th>{items.map(i=><th key={i.id} className={`border-b p-2 text-center ${focusedSizeId===i.id?"border-2 border-warn bg-warn-tint":"border-line"} ${i.active?"":"text-ink-muted"}`}>{i.sizeLabel??i.name}{!i.active&&<span className="block text-[17px]">{labels.inactive}</span>}{focusedSizeId===i.id&&<span className="block text-[17px] text-warn">{i.costStatus==="NO_RECIPE"?labels.noRecipe:i.costStatus==="MISSING_INGREDIENT_COST"?labels.missingCost:labels.focused}</span>}</th>)}</tr></thead><tbody>{rows.map(([ingredientId,name])=><tr key={ingredientId}><th className="border-b border-line p-2 text-start font-semibold">{name}</th>{items.map(item=>{const line=item.recipe.find(l=>l.ingredientId===ingredientId);const addition=additions.find(a=>(a.ingredientId??a.key)===ingredientId&&a.menuItemId===item.id);const key=`${item.id}:${ingredientId}`;const d=drafts[key]??(line?draftForLine(line):undefined);return <td key={item.id} className={`border-b p-2 ${focusedSizeId===item.id?"border-x-2 border-warn bg-warn-tint/40":"border-line"} ${item.active?"":"bg-paper/60"}`}>{line&&d&&!d.removed?<div className="flex items-center justify-center gap-1"><input aria-label={`${name} ${item.sizeLabel??item.name}`} className="h-12 w-20 rounded-lg border border-line px-2" type="number" min="0.01" step="0.01" value={d.quantity} onChange={e=>setDrafts(x=>({...x,[key]:{...d,quantity:e.target.value}}))}/><select className="h-12 rounded-lg border border-line px-1" value={d.unit} onChange={e=>setDrafts(x=>({...x,[key]:{...d,unit:e.target.value as RecipeDisplayUnit}}))}>{recipeDisplayUnitsFor(line.baseUnit,ingredientConversions[line.ingredientId]??[]).map(u=><option key={u} value={u}>{labels[u]??u}</option>)}</select><button type="button" aria-label={`${labels.remove} ${name}`} onClick={()=>setDrafts(x=>({...x,[key]:{...d,removed:true}}))} className="min-h-12 min-w-12 text-warn"><Trash2 size={17} aria-hidden="true"/></button></div>:addition?<div className="flex items-center justify-center gap-2 font-semibold text-good"><span>{addition.quantity} {labels[addition.unit]??addition.unit}</span><button type="button" aria-label={`${labels.remove} ${name}`} onClick={()=>setAdditions(current=>current.filter(a=>a.key!==addition.key))} className="min-h-12 min-w-12 text-warn"><Trash2 size={17}/></button></div>:<button type="button" onClick={()=>setAddTo(item.id)} className="min-h-12 px-3 text-sm font-bold text-good"><Plus size={16} className="inline"/> {labels.add}</button>}</td>})}</tr>)}</tbody></table></div>
 <button type="button" onClick={()=>setAddTo(items[0]?.id??null)} className="mt-3 min-h-12 text-start font-bold text-good"><Plus className="me-2 inline" size={18}/>{labels.addIngredient}</button>
 {addTo&&<div className="mt-2 rounded-xl border border-line p-3"><p className="font-bold">{labels.addTo} {items.find(i=>i.id===addTo)?.sizeLabel}</p><div className="mt-2 grid grid-cols-3 gap-1">{(["g","ml","each"] as const).map(k=><button type="button" key={k} onClick={()=>{setKind(k);setSelected(null);setUnit(k)}} className={`min-h-12 rounded-full border text-sm font-bold ${kind===k?"border-ink bg-ink text-paper":"border-line"}`}>{labels[k]}</button>)}</div>{!creating&&<><label className="mt-2 flex min-h-12 items-center rounded-lg border border-line px-3"><Search size={16}/><input className="min-w-0 flex-1 px-2 outline-none" value={search} onChange={e=>setSearch(e.target.value)} placeholder={labels.search}/></label><div className="max-h-40 overflow-y-auto">{filtered.map(i=><button type="button" key={i.id} onClick={()=>chooseIngredient(i)} className={`flex min-h-12 w-full items-center px-2 text-start ${selected?.id===i.id?"bg-good-tint font-bold":""}`}>{i.name}</button>)}</div><button type="button" onClick={()=>{setCreating(true);setSelected(null);setUnit(kind)}} className="min-h-12 font-bold text-good">{labels.create}</button></>}{creating&&<label className="mt-2 block font-semibold">{labels.name}<input className="mt-1 h-12 w-full rounded-lg border border-line px-3" value={newName} onChange={e=>setNewName(e.target.value)}/></label>}{(selected||creating)&&<><label className="mt-2 block font-semibold">{labels.unit}<select className="mt-1 h-12 w-full rounded-lg border border-line px-3" value={unit} onChange={e=>setUnit(e.target.value as RecipeDisplayUnit)}>{selectedUnits.map(value=><option key={value} value={value}>{labels[value]??value}</option>)}</select></label><label className="mt-2 block font-semibold">{labels.quantity}<input className="mt-1 h-12 w-full rounded-lg border border-line px-3" type="number" min="0.01" step="0.01" value={quantity} onChange={e=>setQuantity(e.target.value)}/></label></>}<div className="mt-3 grid grid-cols-2 gap-2"><button type="button" onClick={resetAdd} className="min-h-12 rounded-full border border-line font-bold">{labels.cancel}</button><button type="button" disabled={pending} onClick={stageAdd} className="min-h-12 rounded-full bg-ink font-bold text-paper disabled:opacity-40">{labels.add}</button></div></div>}
 {error&&<p className="mt-3 font-semibold text-warn">{error}</p>}{saved&&<p className="mt-3 font-semibold text-good">{labels.saved}</p>}<div className="mt-4 grid grid-cols-2 gap-2"><button type="button" disabled={pending} onClick={cancel} className="min-h-12 rounded-full border border-line font-bold">{labels.cancel}</button><button type="button" disabled={pending} onClick={save} className="min-h-12 rounded-full bg-ink font-bold text-paper disabled:opacity-40">{labels.saveRecipe}</button></div></section>;
}
